modified host workflow

diff --git a/.github/workflows/host-build.yml b/.github/workflows/host-build.yml
--- a/.github/workflows/host-build.yml
+++ b/.github/workflows/host-build.yml
@@ -37,15 +37,6 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
-    
-    - name: Wait for database to be ready
-      run: |
-        for i in {1..10}; do
-          nc -z localhost 5432 && echo "Database is up" && exit 0
-          echo "Waiting for database..."
-          sleep 5
-        done
-        echo "Database failed to start" && exit 1
 
     - name: Setup dotnet
       uses: actions/setup-dotnet@v3
@@ -58,8 +49,20 @@ jobs:
     - name: Build projects
       run: dotnet build
 
+    - name: Wait for database to be ready
+      run: |
+        for i in {1..10}; do
+          nc -z localhost 5432 && echo "Database is up" && exit 0
+          echo "Waiting for database..."
+          sleep 5
+        done
+        echo "Database failed to start" && exit 1
+
     - name: Run unit tests
       run: dotnet test ./test/PostsByMarko.UnitTests
 
     - name: Run integration tests
+      env:
+        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=postsbymarko;Username=${{ env.DB_USER }};Password=${{ env.DB_PASSWORD }}"
+        ASPNETCORE_ENVIRONMENT: Test
       run: dotnet test ./test/PostsByMarko.IntegrationTests
